"""fix_user_created_at_default2

Revision ID: 3c8dfdbc8755
Revises: 64090c0e935e
Create Date: 2026-03-11 23:43:02.818629

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3c8dfdbc8755"
down_revision: str | Sequence[str] | None = "64090c0e935e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
