"""add isAdmin

Revision ID: 56824abe8ad3
Revises: be12604c1023
Create Date: 2026-04-26 19:16:13.657973

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "56824abe8ad3"
down_revision: Union[str, Sequence[str], None] = "be12604c1023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
