"""add isAdmin

Revision ID: be12604c1023
Revises: f50dae050f7c
Create Date: 2026-04-26 18:52:19.838605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be12604c1023"
down_revision: Union[str, Sequence[str], None] = "f50dae050f7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_tokens_token"), table_name="user_tokens")
    op.create_index(
        op.f("ix_user_tokens_token"), "user_tokens", ["token"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "isAdmin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_index(op.f("ix_users_isAdmin"), "users", ["isAdmin"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_isAdmin"), table_name="users")
    op.drop_column("users", "isAdmin")
    op.drop_index(op.f("ix_user_tokens_token"), table_name="user_tokens")
    op.create_index(op.f("ix_user_tokens_token"), "user_tokens", ["token"], unique=True)
    # ### end Alembic commands ###
