services:
  backend:
    build:
      context: .
      dockerfile: back_seller/Dockerfile
    container_name: pius_backend
    ports:
      - "8002:8002"
    volumes:
      - ./back_seller:/app
    env_file:
      - ./back_seller/.env
    depends_on:
      - seller_postgres
    networks:
      - shared_net
    command: >
      sh -c "
      echo 'Waiting for Postgres...' &&
      until pg_isready -h seller_postgres -U postgres; do
        sleep 2;
      done;

      echo 'Running migrations...' &&
      alembic upgrade head &&

      echo 'Starting backend...' &&
      uvicorn app.main:app --host 0.0.0.0 --port 8002
      "

  frontend:
    build:
      context: .
      dockerfile: seller-frontend/Dockerfile
    container_name: pius_frontend
    ports:
      - "5172:5172"
    volumes:
      - ./seller-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - shared_net

  seller_postgres:
    image: postgres:16
    container_name: pius_db
    hostname: seller_postgres
    restart: always
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared_net

volumes:
  pg_data:

networks:
  shared_net:
    name: pius_global_network
