version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: user_service_db
    hostname: user-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - shared_net

  api:
    build: .
    container_name: user_service_api
    deploy:
      resources:
        limits:
          memory: 5120M
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./logreg:/app/logreg
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head &&
             python src/app/main.py"
    networks:
      - shared_net

  api-tests:
    build: .
    container_name: app_tests
    environment:
      - DATABASE_URL=${TEST_DATABASE_URL}
      - SELLER_SERVICE_URL=${SELLER_SERVICE_URL}
    depends_on:
      - postgres
    networks:
      - shared_net
    command: pytest tests/ --cov=src --cov-report=term-missing

  frontend-auth:
    build:
      context: ../general-login-front
    container_name: user_auth_frontend
    ports:
      - "5173:5173"
    volumes:
      - ../general-login-front:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - shared_net

  frontend-user:
    build:
      context: ../user-frontend
    container_name: user_main_frontend
    ports:
      - "5171:5171"
    volumes:
      - ../user-frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - shared_net

volumes:
  postgres_data:

networks:
  shared_net:
    name: pius_global_network
