services:
  frontend:
    build:
      context: ../general-login-front
    container_name: user_service_frontend
    ports:
      - "5173:5173"
    volumes:
      - ../general-login-front:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    networks:
      - shared_net

  api:
    build: .
    container_name: user_service_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./logreg:/app/logreg
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=user_service_db
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head &&
             python src/app/main.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/cart/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shared_net

  frontend-user:
    build:
      context: ../user-frontend
    container_name: user_main_frontend
    ports:
      - "5171:5171"
    volumes:
      - ../user-frontend:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    networks:
      - shared_net

  postgres:
    image: postgres:16
    container_name: user_service_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shared_net

volumes:
  postgres_data:

networks:
  shared_net:
    name: pius_global_network
